### ISSUE TITLE
测试test.c时出现错误，无法生成test可运行程序，应该如何解决

### ISSUE THREAD

**Issue by TimeAgent-X** [pandolia/tinyc#1]
user@USER:~/tinyc/tinyc$ tcc test.c
ld: /home/wsxnh/tinyc/tinyc/release/libtio.a(tio.o): in function `PRINT':
tio.c:(.text+0x1e6): undefined reference to `__stack_chk_fail_local'
ld: /home/wsxnh/tinyc/tinyc/release/libtio.a(tio.o): in function `READINT':
tio.c:(.text+0x397): undefined reference to `__stack_chk_fail_local'
ld: test: hidden symbol `__stack_chk_fail_local' isn't defined
ld: 最后的链结失败: bad value
mv: 对 'test' 调用 stat 失败: 没有那个文件或目录

**Comment by TimeAgent-X** [comment]
已解决。

**Comment by pandolia** [comment]
是啥问题呀？

**Comment by LIFE-SI** [comment]
Linux系统兼容性问题，已经解决了，谢谢

**Comment by TimeAgent-X** [comment]
Linux系统兼容性问题，已通过更换系统解决。
